
#_OBJECTIVE: USE A FOR LOOP TO GENERATE AND PRINT THE MULTIPLICATION TABLE FOR A GIVEN NUMBER.

X = int(input('ENTER A NUMBER TO SEE ITS MULTIPLICATION TABLE:'))

for Y in range(1, 11):
    Z = X * Y 
    print(X, '*', Y, '=', Z)